on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: CloudFormation Linting and Static Analysis
jobs:
  cloudformation-jobs:
    runs-on: ubuntu-latest
    name: CloudFormation-jobs
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          path: src/github.com/${{ github.repository }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Setup cfn-lint & checkov
        run: |
          pip3 install cfn-lint checkov
          echo "::add-matcher::.github/workflows/problemMatchers/cfn-lint.json"
          echo "::add-matcher::.github/workflows/problemMatchers/checkov-problem-matcher.json"
      
      - name: Lint Cloudformation templates
        if: success() || failure()
        run: cfn-lint *.yaml -i E2532 E3002 E1019 W2001

      - name: Checkov Static Analysis
        if: success() || failure()
        run: |
          checkov -d . --skip-check CKV_AWS_18,CKV_AWS_21,CKV_AWS_66,CKV_AWS_60 --quiet
